#!/bin/bash

g++ -std=c++11 -Wall -Werror -pedantic-errors -I ../include -DNDEBUG Auxiliaries.cpp Character.cpp Game.cpp Medic.cpp Soldier.cpp Sniper.cpp partC_tester.cpp -g

valgrind --leak-check=full ./a.out